### ISSUE TITLE
How do i obtain a blank board? 

### ISSUE THREAD

**Issue by halfaipg** [jbilander/SF500#3]
Anywhere I can buy? I'm not familiar with having PCBs printed.

**Comment by dlxmax** [comment]
Yes, please share the gerbers on PCBWay's Shared Projects so that we can buy individual boards, and you get a little cut of the action too. Thanks!
https://www.pcbway.com/project/shareproject/

**Comment by jbilander** [comment]
Hi, gerbers + drill files are available in a zip-file under _**Releases**_. You just have to upload the zip-file to your boardhouse e.g. JLCPCB.

**Comment by dlxmax** [comment]
I suggested putting it up on Shared Projects because it allows people to buy just one board instead of the otherwise minimum 10.
Most of us would have 9 boards sitting in a drawer, which is uncomfortably wasteful ;)

**Comment by halfaipg** [comment]
Thanks guys, very helpful. I uploaded the gerber files to shared projects on PCBWay.com and its under review. 

Another question, what device do I need to program the rom chip?

**Comment by halfaipg** [comment]
Okay, when I add my shared project to cart on PCBWay, it detects the board as only being 2 layers but I see in the notes that it is a 4 layer board.

**Comment by blockchainbulls** [comment]
https://www.pcbway.com/project/shareproject/Spit_Fire_500___14mhz_Amiga_500_Accelerator_card.html

**Comment by jbilander** [comment]
Hi, please remove the link to pcbway here on github (comment above) so people don't think I'm in any way linked to the donations you will receive from this. I only do Amiga stuff for a hobby. Not to make Money. Thanks
