### ISSUE TITLE
BOM error

### ISSUE THREAD

**Issue by perhof** [jbilander/SF500#6]
Hi,

Good job with the accellerator!

There's a minor error in the BOM regarding the decoupling caps for the SRAM. It says C5-C6 is for first 4MBs (U5-U6) and C7-C8 is for second optional 4MBs (U7-U8) which would have made sense and all but it's in fact C6 & C7 that is for the first 4MB and C5 & C8 is for the second 4MB. I thinkl people get it but might as well correct it, either in the BOM or in the schematic.

Some experiences that I'd want to share...

I used an SST39SF010 1mbit flash chip instead of the 29F040 because I had plenty on hand and it's pin compatible. SST39SF020 and SST39SF040 would have worked too. Could be an option if/when 29F040 are out of stock.

For the clock multipler, I couldn't get a NB3N502 because of the shortage but a Renesas 502MLF‎ worked just as well.

To bad the SRAM is so hard to get. Where did you find them at €4.18?
I had to buy the CY62167GE with ECC and it was much more expensive and was also in limited supply.  Do you think the CY62167GN-45ZXI would work? It's a little bit cheaper than the GE.

For the machined pins I pulled pins out of machined 40-pin header rows which are cheaper than the loose pins and I already had them on stock.
If the holes weren't drilled for machine pins I would have used this kind instead: https://www.aliexpress.com/item/4000106121057.html
They are durable and sits very well in sockets. Much harder to break than the machined pins too.
They are long so I stick them through the PCB from above and into a socket, then solder from above and cut off the remaining part. 
If I need to build another SF500 I might make a variant for this.

It's also hard to use it with Rev 5 A500 PCBs where you need an adapter for the Kickstart ROM if you are going to use a newer ROM than the original 1.2/1.3 unless you modify the motherboard.

Finally I spent a whole lot of time troubleshooting the disk controller and I even built a second board because I though there was something wrong with my first build. Turned out it was an incompatibility with my CompactFlash card. which was a Transcend CompactFlash 800 32GB card. It just locked up the whole controller and computer as soon as it was attached and the controller was enabled. Couldn't boot from floppy either. Activity light on CF adapter was steady on.
Might want to stay away from that CF model.

Vi säger så :)
Mvh Per

**Comment by jbilander** [comment]
Hi, thanks for sharing your findings. I'm glad you like it.

Actually the BOM is correct.
Capacitors being on the flipside has to do with limited board space for placing and routing, decoupling is for VCC-input on pin 37, VCC on pin 12 is only to hold CE2 high, it isn't neccessary but it doesn't hurt anything if you populate C7-C8 too in a two-chip-configuration (4 MB) build.

Regarding SRAM. I think CY62167GN-45ZXI and CY62167ELL-45ZXI should work as replacements, I haven't scrutinized the datasheets but taking a quick peek they seem almost identical. The Amiga is TTL logic levels so should be compatible with those logic levels from them SRAM-chips.

CY62167ELL-45ZXI can perhaps be sourced cheaply from link below, if they are genuine Cypress?, I don't know. They are only a quarter of the unit price at Mouser. When I designed this Accelerator there was no chip shortage and Digikey sold the Chips for unit price €4,18 with no warranty. The choice was easy. That's not the case now.

https://www.aliexpress.com/item/1005003256658439.html

Regarding A500 Rev 3 and Rev 5. You can make this low profile Kickstart ROM-switch mod and it shouldn't be a problem with clearance:
https://youtu.be/jSbbypYNPsk?t=1102

Regarding using the pins from the Stackable Long Legs Female Header. Aren't those too thick square-pins for the dip 64-pin socket sitting in the Amiga? If not they could work if you solder them at the correct length and in level. You see my first revision (1A) was with these kind of pins: https://www.aliexpress.com/item/32887861343.html  but the accelerator became too elevated touching the underside of the keyboard so you couldn't close the case. It's important to get the correct height to both give clearance for the 86-pin metal-shield to the left and the ROM-chip to the right (when the CF-adapter is installed). With using the pins in the BOM you get just that:
https://github.com/jbilander/SF500/blob/main/images/SF500_rev1b_pic6.jpg

Regards, J

**Comment by perhof** [comment]
I will populate the caps on the bottom too then. I was going to sooner or later anyway but I need to get some more RAM first.

The CY62167ELL looks interesting. Good find! I will order some some from Counterfeitexpress and try :)

I have already designed a ROM adapter with an offset ROM so it relocates the ROM to the space between the ROM socket and the Agnus. I think that should do it.
I also had to replace an electrolytic cap on the rev 5 PCB near the pin 1 end of the 68k socket. It was a bit too tall for the PCB to clear it and the legs were to short to fold it out of the way. I put in a new cap and kept enough of the legs to be able to fold it away.

The machined pins you used in your first version is what I used too but I used them differently. I stripped all the plastic to get just get to the pins inside and populated them from the top of the PCB and cut away the remaning little tip on the top.

The stackable long headers are not square, they are flat so they are more like chip pins and they fit very well in sockets. The machined round ones have a tendency of falling out of dual wipe sockets. The flat ones don't do that. The socket gets a really secure grip on the pins and the pins don't destroy the socket as the square ones do. The downside is that they are a little bit trickier to solder because there is no frame on them that can be used to align them to the PCB. You have to use a socket under the PCB to keep both sideway position and elevation.
It doesn't show the shape of the pins very well in my pictures but I can send you a few samples if you would like to check them out.

![20220115_113148](https://user-images.githubusercontent.com/1810367/149619244-7cff3715-6388-44ea-b742-eb2daf099614.jpg)
![20220115_113230](https://user-images.githubusercontent.com/1810367/149619247-0194faff-de2c-4c60-be5b-f0b13f427fbf.jpg)
![20220115_115400](https://user-images.githubusercontent.com/1810367/149619248-5c5abb6b-89a7-4b9d-915d-c09f0a9cfd31.jpg)

**Comment by perhof** [comment]
For your info, I purchased the CY62167ELL-45ZXI chips from https://www.aliexpress.com/item/1005003256658439.html for $3 each and they seem to work just fine.

**Comment by jbilander** [comment]
Great to hear :)  ,thanks for the info. I will add it to the BOM...and thanks for showing the method of how-to use the stackable long headers.
